INFO     root:controllers.py:47 Data inserted: hound, https://images.dog.ceo/breeds/hound-english/n02089973_3688.jpg, 200
WARNING  root:app.py:39 Breed 'invalid_breed' not found (404)
ERROR    root:app.py:47 Timeout error occurred: 
INFO     root:controllers.py:47 Data inserted: hound, https://images.dog.ceo/breeds/hound/image.jpg, 200
