INFO     root:controllers.py:56 Data inserted: hound, https://images.dog.ceo/breeds/hound-blood/n02088466_8904.jpg, 200
WARNING  root:app.py:39 Breed 'invalid_breed' not found (404)
ERROR    root:app.py:47 Timeout error occurred: 
ERROR    root:app.py:56 Error connecting to Dog CEO API: API request failed
INFO     root:controllers.py:56 Data inserted: hound, https://images.dog.ceo/breeds/hound/image.jpg, 200
